import { Venue, Match, Player, User } from "./types";

export const DISTRICTS = [
  "Miraflores",
  "San Isidro",
  "Santiago de Surco",
  "La Molina",
  "San Borja",
  "Barranco",
  "Magdalena del Mar",
  "Jesús María",
  "Pueblo Libre",
  "Lince",
  "San Miguel",
  "Ate",
] as const;

export const venues: Venue[] = [
  {
    id: "venue-1",
    name: "Padel Lima Club",
    address: "Av. El Polo 670",
    district: "Santiago de Surco",
    imageUrl: "/images/venue1.jpg",
    rating: 4.7,
    reviewCount: 342,
    courtCount: 6,
    amenities: ["Estacionamiento", "Duchas", "Pro Shop", "Cafetería", "Casilleros", "WiFi"],
    openTime: "06:00",
    closeTime: "23:00",
    phone: "+51 1 437 2200",
    description: "El club de pádel más completo de Surco con 6 canchas de última generación, escuela de pádel y un ambiente social inigualable.",
  },
  {
    id: "venue-2",
    name: "Miraflores Padel Center",
    address: "Calle Berlín 385",
    district: "Miraflores",
    imageUrl: "/images/venue2.jpg",
    rating: 4.5,
    reviewCount: 218,
    courtCount: 4,
    amenities: ["Estacionamiento", "Duchas", "Cafetería", "Casilleros"],
    openTime: "07:00",
    closeTime: "22:00",
    phone: "+51 1 243 5678",
    description: "Centro de pádel en el corazón de Miraflores. 4 canchas indoor con clima controlado y programas de entrenamiento para todos los niveles.",
  },
  {
    id: "venue-3",
    name: "San Isidro Padel",
    address: "Av. Camino Real 1234",
    district: "San Isidro",
    imageUrl: "/images/venue3.jpg",
    rating: 4.8,
    reviewCount: 156,
    courtCount: 5,
    amenities: ["Estacionamiento", "Duchas", "Fisioterapia", "Bar", "Casilleros", "Zona Kids"],
    openTime: "06:00",
    closeTime: "23:00",
    phone: "+51 1 421 4567",
    description: "Pádel premium en San Isidro. Canchas panorámicas con cristal, coaching profesional y las mejores instalaciones de Lima.",
  },
  {
    id: "venue-4",
    name: "La Molina Padel Arena",
    address: "Av. La Molina 2850",
    district: "La Molina",
    imageUrl: "/images/venue4.jpg",
    rating: 4.3,
    reviewCount: 89,
    courtCount: 8,
    amenities: ["Estacionamiento", "Duchas", "Pro Shop", "Restaurante", "Casilleros", "Piscina"],
    openTime: "06:00",
    closeTime: "23:00",
    phone: "+51 1 368 9012",
    description: "El complejo de pádel más grande de Lima con 8 canchas, restaurante y un ambiente familiar para disfrutar en La Molina.",
  },
  {
    id: "venue-5",
    name: "Barranco Padel Social",
    address: "Av. Grau 450",
    district: "Barranco",
    imageUrl: "/images/venue5.jpg",
    rating: 4.6,
    reviewCount: 275,
    courtCount: 3,
    amenities: ["Duchas", "Bar", "Casilleros", "WiFi", "Alquiler de equipos"],
    openTime: "07:00",
    closeTime: "23:00",
    phone: "+51 1 256 7890",
    description: "Pádel con la mejor onda barranquina. Club social con buen ambiente, torneos semanales y la comunidad más activa de Lima.",
  },
  {
    id: "venue-6",
    name: "San Borja Padel Hub",
    address: "Av. San Borja Sur 780",
    district: "San Borja",
    imageUrl: "/images/venue6.jpg",
    rating: 4.4,
    reviewCount: 134,
    courtCount: 4,
    amenities: ["Estacionamiento", "Duchas", "Cafetería", "Casilleros", "Gimnasio"],
    openTime: "06:00",
    closeTime: "22:00",
    phone: "+51 1 225 3456",
    description: "Centro deportivo integral en San Borja con canchas de pádel indoor, gimnasio y comunidad activa de jugadores.",
  },
  {
    id: "venue-7",
    name: "Magdalena Padel Club",
    address: "Av. Brasil 3200",
    district: "Magdalena del Mar",
    imageUrl: "/images/venue7.jpg",
    rating: 4.2,
    reviewCount: 67,
    courtCount: 3,
    amenities: ["Estacionamiento", "Duchas", "Cafetería", "WiFi"],
    openTime: "07:00",
    closeTime: "22:00",
    phone: "+51 1 461 2345",
    description: "Club acogedor en Magdalena con precios accesibles y una comunidad de jugadores de todos los niveles.",
  },
  {
    id: "venue-8",
    name: "Ate Padel Park",
    address: "Av. Nicolás Ayllón 5200",
    district: "Ate",
    imageUrl: "/images/venue8.jpg",
    rating: 4.1,
    reviewCount: 45,
    courtCount: 5,
    amenities: ["Estacionamiento", "Duchas", "Snack Bar", "Casilleros", "Alquiler de equipos"],
    openTime: "06:00",
    closeTime: "22:00",
    phone: "+51 1 348 7890",
    description: "Pádel accesible en Lima Este. 5 canchas con iluminación LED, torneos de fin de semana y clases para principiantes.",
  },
];

export const players: Player[] = [
  { id: "player-1", name: "Carlos Mendoza", avatarUrl: "", level: 4.2, district: "Miraflores", matchesPlayed: 156, wins: 89, memberSince: "2024-03-15" },
  { id: "player-2", name: "María Quispe", avatarUrl: "", level: 3.8, district: "San Isidro", matchesPlayed: 98, wins: 52, memberSince: "2024-06-01" },
  { id: "player-3", name: "Alejandro Paredes", avatarUrl: "", level: 5.1, district: "Santiago de Surco", matchesPlayed: 234, wins: 167, memberSince: "2023-11-20" },
  { id: "player-4", name: "Lucía Fernández", avatarUrl: "", level: 3.5, district: "La Molina", matchesPlayed: 67, wins: 31, memberSince: "2025-01-10" },
  { id: "player-5", name: "Diego Huamán", avatarUrl: "", level: 4.8, district: "San Borja", matchesPlayed: 189, wins: 121, memberSince: "2024-01-05" },
  { id: "player-6", name: "Ana Rojas", avatarUrl: "", level: 4.0, district: "Barranco", matchesPlayed: 112, wins: 63, memberSince: "2024-04-22" },
  { id: "player-7", name: "Fernando Torres", avatarUrl: "", level: 2.9, district: "Magdalena del Mar", matchesPlayed: 45, wins: 18, memberSince: "2025-06-15" },
  { id: "player-8", name: "Sofía Castillo", avatarUrl: "", level: 3.2, district: "Jesús María", matchesPlayed: 78, wins: 35, memberSince: "2025-02-28" },
  { id: "player-9", name: "Roberto Silva", avatarUrl: "", level: 4.5, district: "San Isidro", matchesPlayed: 201, wins: 132, memberSince: "2023-09-10" },
  { id: "player-10", name: "Valentina Chávez", avatarUrl: "", level: 3.9, district: "Miraflores", matchesPlayed: 88, wins: 49, memberSince: "2024-08-14" },
  { id: "player-11", name: "Gonzalo Ramos", avatarUrl: "", level: 5.3, district: "Santiago de Surco", matchesPlayed: 310, wins: 228, memberSince: "2023-05-01" },
  { id: "player-12", name: "Camila Vega", avatarUrl: "", level: 2.5, district: "Lince", matchesPlayed: 22, wins: 7, memberSince: "2025-10-01" },
];

export const matches: Match[] = [
  {
    id: "match-1",
    venueId: "venue-1",
    venueName: "Padel Lima Club",
    district: "Santiago de Surco",
    date: "2026-02-14",
    time: "18:00",
    level: "intermedio",
    currentPlayers: [players[0], players[1]],
    maxPlayers: 4,
    creator: players[0],
    type: "amistoso",
    gender: "mixto",
    description: "Buscamos 2 jugadores para un partido relajado en la tarde. Nivel intermedio de preferencia.",
    pricePerPlayer: 25,
    duration: 90,
  },
  {
    id: "match-2",
    venueId: "venue-1",
    venueName: "Padel Lima Club",
    district: "Santiago de Surco",
    date: "2026-02-15",
    time: "10:00",
    level: "avanzado",
    currentPlayers: [players[2], players[4], players[8]],
    maxPlayers: 4,
    creator: players[2],
    type: "competitivo",
    gender: "mixto",
    description: "Partido competitivo, falta 1 jugador avanzado. Vengan con ganas!",
    pricePerPlayer: 30,
    duration: 90,
  },
  {
    id: "match-3",
    venueId: "venue-3",
    venueName: "San Isidro Padel",
    district: "San Isidro",
    date: "2026-02-14",
    time: "20:00",
    level: "pro",
    currentPlayers: [players[2], players[10]],
    maxPlayers: 4,
    creator: players[2],
    type: "competitivo",
    gender: "varones",
    description: "Partido de nivel alto. Mínimo nivel 4.5. Canchas panorámicas.",
    pricePerPlayer: 35,
    duration: 90,
  },
  {
    id: "match-4",
    venueId: "venue-5",
    venueName: "Barranco Padel Social",
    district: "Barranco",
    date: "2026-02-16",
    time: "17:00",
    level: "principiante",
    currentPlayers: [players[6], players[11]],
    maxPlayers: 4,
    creator: players[6],
    type: "amistoso",
    gender: "mixto",
    description: "Partido para principiantes! Ven a disfrutar del pádel en un ambiente tranquilo. No importa si recién empiezas.",
    pricePerPlayer: 18,
    duration: 90,
  },
  {
    id: "match-5",
    venueId: "venue-2",
    venueName: "Miraflores Padel Center",
    district: "Miraflores",
    date: "2026-02-15",
    time: "09:00",
    level: "intermedio",
    currentPlayers: [players[1], players[3]],
    maxPlayers: 4,
    creator: players[1],
    type: "amistoso",
    gender: "damas",
    description: "Pádel de mañana solo chicas. Nivel intermedio, buen ambiente.",
    pricePerPlayer: 22,
    duration: 90,
  },
  {
    id: "match-6",
    venueId: "venue-6",
    venueName: "San Borja Padel Hub",
    district: "San Borja",
    date: "2026-02-17",
    time: "19:30",
    level: "avanzado",
    currentPlayers: [players[4]],
    maxPlayers: 4,
    creator: players[4],
    type: "competitivo",
    gender: "mixto",
    description: "Busco 3 jugadores competitivos para un partido intenso en San Borja.",
    pricePerPlayer: 28,
    duration: 90,
  },
  {
    id: "match-7",
    venueId: "venue-4",
    venueName: "La Molina Padel Arena",
    district: "La Molina",
    date: "2026-02-15",
    time: "16:00",
    level: "intermedio",
    currentPlayers: [players[5], players[9]],
    maxPlayers: 4,
    creator: players[5],
    type: "amistoso",
    gender: "mixto",
    description: "Partidito de fin de semana en La Molina. Todos bienvenidos, nivel intermedio.",
    pricePerPlayer: 20,
    duration: 90,
  },
  {
    id: "match-8",
    venueId: "venue-8",
    venueName: "Ate Padel Park",
    district: "Ate",
    date: "2026-02-16",
    time: "08:00",
    level: "principiante",
    currentPlayers: [players[7]],
    maxPlayers: 4,
    creator: players[7],
    type: "amistoso",
    gender: "mixto",
    description: "Mañana temprano en Ate. Ideal para los que quieren empezar el día con deporte.",
    pricePerPlayer: 15,
    duration: 60,
  },
  {
    id: "match-9",
    venueId: "venue-7",
    venueName: "Magdalena Padel Club",
    district: "Magdalena del Mar",
    date: "2026-02-18",
    time: "20:30",
    level: "intermedio",
    currentPlayers: [players[6], players[7], players[9]],
    maxPlayers: 4,
    creator: players[6],
    type: "amistoso",
    gender: "mixto",
    description: "Último lugar! Partido nocturno en Magdalena. Nivel intermedio, buena onda.",
    pricePerPlayer: 18,
    duration: 90,
  },
];

export const currentUser: User = {
  id: "player-1",
  name: "Carlos Mendoza",
  email: "carlos.mendoza@gmail.com",
  phone: "+51 987 654 321",
  avatarUrl: "",
  level: 4.2,
  district: "Miraflores",
  matchesPlayed: 156,
  wins: 89,
  memberSince: "2024-03-15",
  preferredHand: "derecha",
  preferredPosition: "drive",
  upcomingMatches: [matches[0], matches[1]],
  pastMatches: [],
};

export function getVenueById(id: string): Venue | undefined {
  return venues.find((v) => v.id === id);
}

export function getMatchesByVenue(venueId: string): Match[] {
  return matches.filter((m) => m.venueId === venueId);
}

export function getOpenMatches(): Match[] {
  return matches.filter((m) => m.currentPlayers.length < m.maxPlayers);
}

export function getPlayersByLevel(): Player[] {
  return [...players].sort((a, b) => b.level - a.level);
}

export function getTopPlayers(count: number = 10): Player[] {
  return [...players]
    .sort((a, b) => {
      const aWinRate = a.matchesPlayed > 0 ? a.wins / a.matchesPlayed : 0;
      const bWinRate = b.matchesPlayed > 0 ? b.wins / b.matchesPlayed : 0;
      return bWinRate - aWinRate;
    })
    .slice(0, count);
}

export function getPlayersByDistrict(district: string): Player[] {
  return players.filter((p) => p.district === district);
}
